name: Check
'on': push
jobs:
  build:
    name: covr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'covr'), repos = 'https://demo.rstudiopm.com/all/__linux__/focal/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/focal/latest')"
      - name: codecov
        run: Rscript -e "covr::codecov(quiet = FALSE)"
    container: rocker/verse:latest
  rcmdchecker:
    name: Rcmdcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
            Rscript -e "install.packages(c('rcmdcheck', 'remotes'), repos = 'https://demo.rstudiopm.com/all/__linux__/focal/latest')"
            Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/focal/latest')"
      - name: Run Check
        run: Rscript -e "rcmdcheck::rcmdcheck(build_args = '--no-manual', args = '--no-manual', error_on = 'warning')"
    container: rocker/verse:latest
  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/run-rchk@v2
      with:
        setup-only: true
    - name: Install package
      run: |-
         install.packages('remotes', repos = 'https://cran.rstudio.com/')
         remotes::install_local()
      shell: Rscript {0}
    - uses: r-lib/actions/run-rchk@v2
      with:
        run-only: true
  test-r-sanitizers:
    name: ASAN-UBSAN
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: rhub/rocker-gcc-san
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          apt install -y g++
          Rdevel -q -e "install.packages('tinytest')"
          Rdevel CMD build .
          Rdevel CMD INSTALL --install-tests *.tar.gz
          Rdevel -q -e "tinytest::test_all()"
